# Using the PyFaaS's ForecastPack module

In [1]:
import json
import pandas as pd
from pyfaas4i.forecastpack import forecast
from pyfaas4i.forecastpack import install_R

## Reading from a RDS file

To get a forecastpack, send a job using the **faas.run_models()** from the faas submodule and it will appear in your [faas application](https://dashes.4intelligence.com.br/).

In [2]:
# installing necessary R packages
install_R()

Starting installation
Packages have been installed

In [5]:
example_rds = forecast()

In [6]:
example_rds.from_rds('./example_forecastpack.rds')

In [7]:
example_rds.model_list()

    Model Model Type     MAPE    WMAPE      MPE     RMSE
0       0      ARIMA   1.4469   1.4435  -0.2785   2.6669
1       1    comb_BG   1.4591   1.4559  -0.1971   2.6786
2       2  comb_EIG1   1.4613   1.4586  -0.0178   2.6892
3       3  comb_EIG3   1.4613   1.4586  -0.0178   2.6892
4       4    comb_NG   1.4780   1.4754   0.0566   2.7161
5       5   comb_CLS   1.4780   1.4754   0.0566   2.7161
6       6  comb_EIG4   1.5633   1.5578  -1.2645   2.8746
7       7  comb_EIG2   1.6831   1.6773  -1.4123   3.0758
8       8   comb_OLS   4.2394   4.2310  -4.2343   7.1995
9       9  comb_InvW   6.4845   6.4910   6.4845  11.1270
10     10    comb_SA   9.8662   9.8724   9.8662  16.8152
11     11   comb_MED   9.8662   9.8724   9.8662  16.8152
12     12    comb_TA   9.8662   9.8724   9.8662  16.8152
13     13    comb_WA   9.8662   9.8724   9.8662  16.8152
14     14      ARIMA  20.0115  20.0162  20.0115  33.9800
15     15   comb_LAD      NaN      NaN      NaN      NaN

## Exploring the pack

In [12]:
# Listing all the models
example_rds.model_list()

    Model Model Type    MAPE   WMAPE     MPE       RMSE
0       0  comb_InvW  6.1285  6.0294 -0.5399  1846.6957
1       1  comb_EIG4  6.2848  6.1558 -1.2254  1896.6975
2       2  comb_EIG3  6.3291  6.1935 -1.3556  1909.1138
3       3   comb_LAD  6.5422  6.5166  0.5013  1945.5415
4       4    comb_NG  6.5751  6.5348  0.6267  1927.8065
5       5   comb_MED  6.6272  6.5652  0.2162  1941.0503
6       6    comb_TA  6.6272  6.5652  0.2162  1941.0503
7       7    comb_BG  6.6393  6.5324 -0.6658  1961.1064
8       8    comb_WA  6.6480  6.5878  0.2679  1946.6281
9       9   comb_OLS  6.6608  6.6487  1.1696  1959.4736
10     10    comb_SA  6.7120  6.6190 -0.3326  1970.4260
11     11  comb_EIG2  6.7583  6.6346 -0.9652  1996.0155
12     12  comb_EIG1  6.7644  6.6662 -0.4363  1983.4223
13     13      ARIMA  7.1900  7.2833  4.4111  2206.1167
14     14      ARIMA  7.3878  7.5422  4.5433  2352.8711
15     15      ARIMA  7.4078  7.1678 -3.5667  2155.6867
16     16      ARIMA  7.4867  7.2522 -3.5122  2189.3656
17     17      ARIMA  7.5111  7.2756 -3.5411  2195.4933
18     18      ARIMA  7.5578  7.3233 -3.5156  2205.4111
19     19      ARIMA  7.6400  7.4056 -3.4089  2223.2900

In [5]:
# Note that the default ordering is the provided in original forecaspack, thus if you want to reorder the models, you can specify the metric
example_rds.model_list(metric='MAPE')

     Model  Model Type    MAPE    WMAPE     MPE          RMSE
46      46       ARIMA  7.5000  12.9300 -0.7300  6.789949e+06
33      33       Ridge  7.9810  10.6678  0.7308  9.657158e+06
30      30  ElasticNet  8.1603  10.1339 -3.8498  8.022030e+06
28      28       Lasso  8.1863  10.0530 -3.8234  8.124756e+06
29      29       ARIMA  8.1950  10.1000 -0.9300  8.513405e+06
18      18       ARIMA  8.2250   8.4800  5.4900  8.257207e+06
69      69       ARIMA  8.2700  14.8200 -3.4550  6.775037e+06
72      72       ARIMA  8.3400  14.8700 -3.5050  6.822642e+06
23      23       ARIMA  8.5350   9.0200  5.8500  8.642884e+06
36      36          LM  8.6981  11.6015 -8.0285  1.176527e+07
49      49       ARIMA  8.8350  13.2400 -1.3750  7.545341e+06
48      48       ARIMA  8.8700  13.2200 -1.6400  7.528179e+06
43      43       ARIMA  8.8750  12.6800 -0.9600  9.051100e+06
50      50       ARIMA  9.0150  13.2700 -1.6750  7.680416e+06
63      63       ARIMA  9.3800  14.3000 -0.2850  7.655991e+06
124    124       ARIMA  9.6000  18.9300 -4.1300  1.090540e+07
1        1   comb_EIG3  9.6362   7.8167  4.4299  8.918579e+06
130    130       ARIMA  9.6750  19.3800 -4.3850  1.097085e+07
17      17    comb_LAD  9.7082   8.4277  4.6580  9.217105e+06
2        2   comb_EIG4  9.8092   7.8259  3.7184  9.126838e+06

In [35]:
# To get a summary of all the models by model type
example_rds.describe()

Metric              ARIMA    ElasticNet  Forecast Combination            LM  \
MAPE  count  2.230000e+02  1.000000e+00          1.400000e+01  1.000000e+00
      mean   1.949249e+01  8.160300e+00          1.070194e+01  8.698100e+00
      min    7.500000e+00  8.160300e+00          9.636200e+00  8.698100e+00
      max    5.952000e+01  8.160300e+00          1.179600e+01  8.698100e+00
WMAPE count  2.230000e+02  1.000000e+00          1.400000e+01  1.000000e+00
      mean   1.993897e+01  1.013390e+01          8.058193e+00  1.160150e+01
      min    8.080000e+00  1.013390e+01          7.738500e+00  1.160150e+01
      max    5.570000e+01  1.013390e+01          8.427700e+00  1.160150e+01
MPE   count  2.230000e+02  1.000000e+00          1.400000e+01  1.000000e+00
      mean  -2.939081e+00 -3.849800e+00          3.046329e+00 -8.028500e+00
      min   -5.952000e+01 -3.849800e+00          2.093600e+00 -8.028500e+00
      max    2.465500e+01 -3.849800e+00          4.658000e+00 -8.028500e+00
RMSE  count  2.230000e+02  1.000000e+00          1.400000e+01  1.000000e+00
      mean   1.643641e+07  8.022030e+06          9.120261e+06  1.176527e+07
      min    6.775037e+06  8.022030e+06          8.918579e+06  1.176527e+07
      max    4.436234e+07  8.022030e+06          9.512481e+06  1.176527e+07

Metric              Lasso  RandomForest         Ridge
MAPE  count  1.000000e+00  1.000000e+00  1.000000e+00
      mean   8.186300e+00  1.892000e+01  7.981000e+00
      min    8.186300e+00  1.892000e+01  7.981000e+00
      max    8.186300e+00  1.892000e+01  7.981000e+00
WMAPE count  1.000000e+00  1.000000e+00  1.000000e+00
      mean   1.005300e+01  2.265000e+01  1.066780e+01
      min    1.005300e+01  2.265000e+01  1.066780e+01
      max    1.005300e+01  2.265000e+01  1.066780e+01
MPE   count  1.000000e+00  1.000000e+00  1.000000e+00
      mean  -3.823400e+00  5.695000e+00  7.308000e-01
      min   -3.823400e+00  5.695000e+00  7.308000e-01
      max   -3.823400e+00  5.695000e+00  7.308000e-01
RMSE  count  1.000000e+00  1.000000e+00  1.000000e+00
      mean   8.124756e+06  1.584210e+07  9.657158e+06
      min    8.124756e+06  1.584210e+07  9.657158e+06
      max    8.124756e+06  1.584210e+07  9.657158e+06

### By default, the first model (Model == 0) is selected, but any can be selected using the set_model() function.
### The model number can be seen in the **Model** column of the model_list()

### Attributes of the forecast class:
 - **json**: json version of the forecastpack
 - **type**: type of the selected model
 - **sample**: sample of the in_sample data from the selected model
 - **transformation**: transformation done in the selected model's data
 - **RMSE**: The root mean squared error for all windows of the cross-validation for the selected model
 - **RMSE_list**: The root mean squared errors for each window of the cross validation for the selected model
 - **MPE**: The mean percentage error for all windows of the cross-validation for the selected model
 - **MPE_list**: The mean percentage errors for each window of the cross validation for the selected model
 - **MAPE**: The mean absolute percentage error for all windows of the cross-validation for the selected model
 - **MAPE_list**: The mean absolute percentage errors for each window of the cross validation for the selected model
 - **WMAPE**: The weighted mean absolute percentage error for all windows of the cross-validation for the selected model
 - **WMAPE_list**: The weighted mean absolute percentage errors for each window of the cross validation for the selected model
 - **models**: Properties of the chosen model, based on the model type. Those being:
    - *ARIMA*: Dictionary with the coeficients of the model and its residuals
    - *RandomForest*: Dataframe with the feature importances
    - *Regression models(Lasso, Ridge and ElasticNet)*: Dictionary with best tune, model coefficients and variable importances
    - *Regression model(LM)*: Dictionary with best tune
    - *Model combination*: Empty dictionary
 - **infos**: Information regarding the chosen model, based on the model type. Those being:
    - *ARIMA*: Dictionary with the ARIMA order and, if available, the model breakdown
    - *RandomForest*: Hyperparameters of the model
    - *Regression models(Lasso, Ridge and ElasticNet, LM)*: Empty dictionary
    - *Model combination*: Dictionary with the combination method and models used in the combination
 - **data**: Dataframe containing the training data used in the selected model
 - **data_proj**: Dataframe containing the data used for forecasting
 - **forecast**: Dataframe containing the entire time series, with historical and forecasted data

## Reading from a json file

In [21]:
example_json = forecast()

In [22]:
example_json.from_json(path="./example_forecastpack.json")

In [23]:
example_json.model_list()

    Model Model Type    MAPE   WMAPE     MPE       RMSE
0       0  comb_EIG1  3.4927  3.4522 -0.9469  3781.4703
1       1  comb_EIG3  3.4927  3.4522 -0.9469  3781.4703
2       2    comb_SA  3.4939  3.4535 -0.9400  3781.9072
3       3   comb_MED  3.4939  3.4535 -0.9400  3781.9072
4       4    comb_TA  3.4939  3.4535 -0.9400  3781.9072
5       5    comb_WA  3.4939  3.4535 -0.9400  3781.9072
6       6    comb_BG  3.4959  3.4558 -0.9274  3782.7582
7       7    comb_NG  3.5161  3.4784 -0.7998  3795.1502
8       8   comb_CLS  3.5161  3.4784 -0.7998  3795.1502
9       9  comb_InvW  3.5339  3.4983 -0.6777  3806.9567
10     10      ARIMA  3.5400  3.5000 -1.7367  3911.0267
11     11   comb_OLS  3.6305  3.6345  0.5127  3880.3535
12     12      ARIMA  3.6500  3.6267 -0.1600  3951.0767
13     13  comb_EIG4  3.7178  3.6616 -2.0478  4067.6680
14     14  comb_EIG2  3.7661  3.7309 -2.4473  4199.3417
15     15      ARIMA  3.7667  3.6900 -1.1667  3888.8500
16     16      ARIMA  3.8033  3.7733 -0.9233  3925.9233
17     17      ARIMA  3.8233  3.7667 -1.5100  4013.4967
18     18   comb_LAD  4.0350  4.0660  1.4373  4297.9424
19     19      ARIMA  4.0667  3.9767 -0.0567  4202.9167